<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>BoltGives.Desktop.UpdateCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\certificates\*.cer" Link="Certificates\%(Filename)%(Extension)" />
    <InternalsVisibleTo Include="BoltGives.Desktop.Tests" />
  </ItemGroup>
</Project>
